name: 'deploy-pr'

on:
  pull_request

jobs:
  review_app:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          command: review-apps:create
          review_app_name: "${{ github.event.pull_request.base.repo.name }}-review-${{ github.event.pull_request.number }}"
          git_remote_url: 'ssh://dokku@c.iphoting.cc:3022/camo'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  destroy_review_app:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy the review app
        uses: dokku/github-action@v1.4.0
        with:
          command: review-apps:destroy
          review_app_name: "${{ github.event.pull_request.base.repo.name }}-review-${{ github.event.pull_request.number }}"
          git_remote_url: 'ssh://dokku@c.iphoting.cc:3022/camo'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
