name: 'deploy-pr'

on:
  pull_request

env:
  REVIEW_APP_NAME: "${{ github.event.pull_request.base.repo.name }}-review-${{ github.event.pull_request.number }}"
  GIT_REMOTE_URL: 'ssh://dokku@c.iphoting.cc:3022/camo'

jobs:
  create_review_app:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create review app
        uses: dokku/github-action@v1.10.0
        with:
          command: review-apps:create
          review_app_name: ${{ env.REVIEW_APP_NAME }}
          git_remote_url: ${{ env.GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy_review_app:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'opened' && github.event.action != 'closed'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to review app
        uses: dokku/github-action@v1.10.0
        with:
          review_app_name: ${{ env.REVIEW_APP_NAME }}
          git_remote_url: ${{ env.GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  destroy_review_app:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
      - name: Destroy review app
        uses: dokku/github-action@v1.10.0
        with:
          command: review-apps:destroy
          review_app_name: ${{ env.REVIEW_APP_NAME }}
          git_remote_url: ${{ env.GIT_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
