name: Ruby

on:
  push:
    branches:
      - master
      - dokku
      - dokku**
  pull_request:
    branches:
      - master
      - dokku
      - dokku**

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test.gemfile
      CAMO_KEY: "test-secret-key"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.9'
        bundler-cache: true
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: npm
    - name: Install Node deps
      run: npm ci
    - name: Build server
      run: npm run build
    - name: Run camo server
      run: |
        node --version
        npm --version
        node server.js &
    - name: Run tests
      run: rake test
